### ISSUE TITLE
현재 해야 할 것들 

### ISSUE THREAD

**Issue by LEEHEESEO** [Burna0912/team_project#9]
1. 시작 메뉴창 만들기
-> 시각적인 디자인 필요, 시작 버튼, 혹 가능하다면 캐릭터 선택창을 만들어서 각 다른 옷을 입고 있는 부로 플레이 할 수 있도록 하면 좋을 듯.(이 경우 계절/학기 별로 부 옷이 달라지게 하는 기능은 삭제해도 좋겠음)

2. 부 애니메이션 만들기
-> 걷는 효과 까지는 무리일 듯 하니, 이미지 좌우 반전으로 이미지를 두 개 만들어서 방향 구분 정도만 하면 될 듯

3. 학점 아이템 이미지
--> 학점 이미지들 만들어서 삽입, 그리고 각 학점이 랜덤하게 내려올 수 있도록 하는 코드 필요. 

4. 학점 충돌
-> 부와 학점이 충돌했을 경우 점수에 변화가 생기도록 하는 코드 필요. 점수를 화면 오른쪽 상단에 띄우는 작업도 필요 

5. 게임 종료 화면 만들기
-> 단순히 "Game Over" 라고 띄우면 재시작을 위해 게임을 껐다 켜야 하는 문제가 발생하므로, 종료 버튼과 재시작 버튼을 만들어 재시작 없이도 게임이 순환될 수 있도록 해야 할 듯. 또한 플레이어의 플레이 미스로 게임이 종료된 것이 아니라 단순 시간 종료이므로, "Game Over" 라는 문구 대신 "Time Over", 암울한 디자인 대신 밝은 분위기의 디자인 화면을 띄우는 게 좋을 듯 함

**Comment by LDY0912** [comment]
clear
